# Foundation CLI/TUI tools - sorted alphabetically
brew "atuin"
brew "bat"
brew "btop"
brew "carapace"
brew "clipboard"
brew "direnv"
brew "dvc"
brew "espanso"
brew "eza"
brew "ffmpeg"
brew "fzf"
brew "gdu"
brew "gh"
brew "ghostty"
brew "git"
brew "git-lfs"
brew "jj"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "neovim"
brew "starship"
brew "stow"
brew "uv"
brew "yazi"
brew "yq"
brew "zoxide"

# Casks - sorted alphabetically
cask "karabiner-elements"
